# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import xml_service_pb2 as xml__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XMLServiceStub(object):
    """Serviço gRPC para operações XML
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreXML = channel.unary_unary(
                '/xmlservice.XMLService/StoreXML',
                request_serializer=xml__service__pb2.StoreXMLRequest.SerializeToString,
                response_deserializer=xml__service__pb2.StoreXMLResponse.FromString,
                _registered_method=True)
        self.GetXML = channel.unary_unary(
                '/xmlservice.XMLService/GetXML',
                request_serializer=xml__service__pb2.GetXMLRequest.SerializeToString,
                response_deserializer=xml__service__pb2.XMLResponse.FromString,
                _registered_method=True)
        self.ListXMLs = channel.unary_unary(
                '/xmlservice.XMLService/ListXMLs',
                request_serializer=xml__service__pb2.Empty.SerializeToString,
                response_deserializer=xml__service__pb2.ListXMLResponse.FromString,
                _registered_method=True)
        self.QueryXPath = channel.unary_unary(
                '/xmlservice.XMLService/QueryXPath',
                request_serializer=xml__service__pb2.XPathRequest.SerializeToString,
                response_deserializer=xml__service__pb2.XPathResponse.FromString,
                _registered_method=True)
        self.ConvertToJSON = channel.unary_unary(
                '/xmlservice.XMLService/ConvertToJSON',
                request_serializer=xml__service__pb2.ConvertToJSONRequest.SerializeToString,
                response_deserializer=xml__service__pb2.ConvertToJSONResponse.FromString,
                _registered_method=True)
        self.ValidateXML = channel.unary_unary(
                '/xmlservice.XMLService/ValidateXML',
                request_serializer=xml__service__pb2.ValidateXMLRequest.SerializeToString,
                response_deserializer=xml__service__pb2.ValidateXMLResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/xmlservice.XMLService/Ping',
                request_serializer=xml__service__pb2.Empty.SerializeToString,
                response_deserializer=xml__service__pb2.XMLResponse.FromString,
                _registered_method=True)


class XMLServiceServicer(object):
    """Serviço gRPC para operações XML
    """

    def StoreXML(self, request, context):
        """Armazena um documento XML no MongoDB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetXML(self, request, context):
        """Recupera um documento XML pelo ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListXMLs(self, request, context):
        """Lista todos os XMLs armazenados
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryXPath(self, request, context):
        """Executa consulta XPath sobre XML armazenado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertToJSON(self, request, context):
        """Converte XML armazenado para JSON
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateXML(self, request, context):
        """Valida XML contra schema XSD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping para testar conectividade
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XMLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreXML': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreXML,
                    request_deserializer=xml__service__pb2.StoreXMLRequest.FromString,
                    response_serializer=xml__service__pb2.StoreXMLResponse.SerializeToString,
            ),
            'GetXML': grpc.unary_unary_rpc_method_handler(
                    servicer.GetXML,
                    request_deserializer=xml__service__pb2.GetXMLRequest.FromString,
                    response_serializer=xml__service__pb2.XMLResponse.SerializeToString,
            ),
            'ListXMLs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListXMLs,
                    request_deserializer=xml__service__pb2.Empty.FromString,
                    response_serializer=xml__service__pb2.ListXMLResponse.SerializeToString,
            ),
            'QueryXPath': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryXPath,
                    request_deserializer=xml__service__pb2.XPathRequest.FromString,
                    response_serializer=xml__service__pb2.XPathResponse.SerializeToString,
            ),
            'ConvertToJSON': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertToJSON,
                    request_deserializer=xml__service__pb2.ConvertToJSONRequest.FromString,
                    response_serializer=xml__service__pb2.ConvertToJSONResponse.SerializeToString,
            ),
            'ValidateXML': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateXML,
                    request_deserializer=xml__service__pb2.ValidateXMLRequest.FromString,
                    response_serializer=xml__service__pb2.ValidateXMLResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=xml__service__pb2.Empty.FromString,
                    response_serializer=xml__service__pb2.XMLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xmlservice.XMLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xmlservice.XMLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XMLService(object):
    """Serviço gRPC para operações XML
    """

    @staticmethod
    def StoreXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/StoreXML',
            xml__service__pb2.StoreXMLRequest.SerializeToString,
            xml__service__pb2.StoreXMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/GetXML',
            xml__service__pb2.GetXMLRequest.SerializeToString,
            xml__service__pb2.XMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListXMLs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/ListXMLs',
            xml__service__pb2.Empty.SerializeToString,
            xml__service__pb2.ListXMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryXPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/QueryXPath',
            xml__service__pb2.XPathRequest.SerializeToString,
            xml__service__pb2.XPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertToJSON(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/ConvertToJSON',
            xml__service__pb2.ConvertToJSONRequest.SerializeToString,
            xml__service__pb2.ConvertToJSONResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/ValidateXML',
            xml__service__pb2.ValidateXMLRequest.SerializeToString,
            xml__service__pb2.ValidateXMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/Ping',
            xml__service__pb2.Empty.SerializeToString,
            xml__service__pb2.XMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
