# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xml_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'xml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11xml_service.proto\x12\nxmlservice\"\x07\n\x05\x45mpty\"8\n\x0fStoreXMLRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x13\n\x0bxml_content\x18\x02 \x01(\t\"D\n\x10StoreXMLResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06xml_id\x18\x03 \x01(\t\"\x1f\n\rGetXMLRequest\x12\x0e\n\x06xml_id\x18\x01 \x01(\t\"V\n\x0bXMLResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x13\n\x0bxml_content\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"2\n\x0cXPathRequest\x12\x0e\n\x06xml_id\x18\x01 \x01(\t\x12\x12\n\nexpression\x18\x02 \x01(\t\"B\n\rXPathResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07results\x18\x02 \x03(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"Y\n\x0fListXMLResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12&\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x17.xmlservice.XMLFileInfo\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"C\n\x0bXMLFileInfo\x12\x0e\n\x06xml_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\"&\n\x14\x43onvertToJSONRequest\x12\x0e\n\x06xml_id\x18\x01 \x01(\t\"O\n\x15\x43onvertToJSONResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0cjson_content\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\x9a\x03\n\nXMLService\x12\x45\n\x08StoreXML\x12\x1b.xmlservice.StoreXMLRequest\x1a\x1c.xmlservice.StoreXMLResponse\x12<\n\x06GetXML\x12\x19.xmlservice.GetXMLRequest\x1a\x17.xmlservice.XMLResponse\x12:\n\x08ListXMLs\x12\x11.xmlservice.Empty\x1a\x1b.xmlservice.ListXMLResponse\x12\x41\n\nQueryXPath\x12\x18.xmlservice.XPathRequest\x1a\x19.xmlservice.XPathResponse\x12T\n\rConvertToJSON\x12 .xmlservice.ConvertToJSONRequest\x1a!.xmlservice.ConvertToJSONResponse\x12\x32\n\x04Ping\x12\x11.xmlservice.Empty\x1a\x17.xmlservice.XMLResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=33
  _globals['_EMPTY']._serialized_end=40
  _globals['_STOREXMLREQUEST']._serialized_start=42
  _globals['_STOREXMLREQUEST']._serialized_end=98
  _globals['_STOREXMLRESPONSE']._serialized_start=100
  _globals['_STOREXMLRESPONSE']._serialized_end=168
  _globals['_GETXMLREQUEST']._serialized_start=170
  _globals['_GETXMLREQUEST']._serialized_end=201
  _globals['_XMLRESPONSE']._serialized_start=203
  _globals['_XMLRESPONSE']._serialized_end=289
  _globals['_XPATHREQUEST']._serialized_start=291
  _globals['_XPATHREQUEST']._serialized_end=341
  _globals['_XPATHRESPONSE']._serialized_start=343
  _globals['_XPATHRESPONSE']._serialized_end=409
  _globals['_LISTXMLRESPONSE']._serialized_start=411
  _globals['_LISTXMLRESPONSE']._serialized_end=500
  _globals['_XMLFILEINFO']._serialized_start=502
  _globals['_XMLFILEINFO']._serialized_end=569
  _globals['_CONVERTTOJSONREQUEST']._serialized_start=571
  _globals['_CONVERTTOJSONREQUEST']._serialized_end=609
  _globals['_CONVERTTOJSONRESPONSE']._serialized_start=611
  _globals['_CONVERTTOJSONRESPONSE']._serialized_end=690
  _globals['_XMLSERVICE']._serialized_start=693
  _globals['_XMLSERVICE']._serialized_end=1103
# @@protoc_insertion_point(module_scope)
