# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_service_pb2 as data__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """======================
    SERVIÇO RPC
    ======================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetXML = channel.unary_unary(
                '/dataset.DataService/GetXML',
                request_serializer=data__service__pb2.Empty.SerializeToString,
                response_deserializer=data__service__pb2.XMLResponse.FromString,
                _registered_method=True)
        self.QueryXPath = channel.unary_unary(
                '/dataset.DataService/QueryXPath',
                request_serializer=data__service__pb2.XPathRequest.SerializeToString,
                response_deserializer=data__service__pb2.XPathResponse.FromString,
                _registered_method=True)
        self.InsertToDB = channel.unary_unary(
                '/dataset.DataService/InsertToDB',
                request_serializer=data__service__pb2.Empty.SerializeToString,
                response_deserializer=data__service__pb2.InsertResponse.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """======================
    SERVIÇO RPC
    ======================

    """

    def GetXML(self, request, context):
        """Devolve o XML completo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryXPath(self, request, context):
        """Executa uma expressão XPath no XML
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertToDB(self, request, context):
        """Insere os dados do XML na base de dados PostgreSQL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetXML': grpc.unary_unary_rpc_method_handler(
                    servicer.GetXML,
                    request_deserializer=data__service__pb2.Empty.FromString,
                    response_serializer=data__service__pb2.XMLResponse.SerializeToString,
            ),
            'QueryXPath': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryXPath,
                    request_deserializer=data__service__pb2.XPathRequest.FromString,
                    response_serializer=data__service__pb2.XPathResponse.SerializeToString,
            ),
            'InsertToDB': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertToDB,
                    request_deserializer=data__service__pb2.Empty.FromString,
                    response_serializer=data__service__pb2.InsertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataset.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataset.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """======================
    SERVIÇO RPC
    ======================

    """

    @staticmethod
    def GetXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataset.DataService/GetXML',
            data__service__pb2.Empty.SerializeToString,
            data__service__pb2.XMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryXPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataset.DataService/QueryXPath',
            data__service__pb2.XPathRequest.SerializeToString,
            data__service__pb2.XPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertToDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataset.DataService/InsertToDB',
            data__service__pb2.Empty.SerializeToString,
            data__service__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
