# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_service.proto\x12\x07\x64\x61taset\"\x07\n\x05\x45mpty\"\x1f\n\x0bXMLResponse\x12\x10\n\x08xml_data\x18\x01 \x01(\t\"\"\n\x0cXPathRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\" \n\rXPathResponse\x12\x0f\n\x07results\x18\x01 \x03(\t\"2\n\x0eInsertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb1\x01\n\x0b\x44\x61taService\x12.\n\x06GetXML\x12\x0e.dataset.Empty\x1a\x14.dataset.XMLResponse\x12;\n\nQueryXPath\x12\x15.dataset.XPathRequest\x1a\x16.dataset.XPathResponse\x12\x35\n\nInsertToDB\x12\x0e.dataset.Empty\x1a\x17.dataset.InsertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=31
  _globals['_EMPTY']._serialized_end=38
  _globals['_XMLRESPONSE']._serialized_start=40
  _globals['_XMLRESPONSE']._serialized_end=71
  _globals['_XPATHREQUEST']._serialized_start=73
  _globals['_XPATHREQUEST']._serialized_end=107
  _globals['_XPATHRESPONSE']._serialized_start=109
  _globals['_XPATHRESPONSE']._serialized_end=141
  _globals['_INSERTRESPONSE']._serialized_start=143
  _globals['_INSERTRESPONSE']._serialized_end=193
  _globals['_DATASERVICE']._serialized_start=196
  _globals['_DATASERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
